/**
 * One explanation per absence, and it lives where it is computed.
 *
 * WHY THIS FILE EXISTS
 *
 * /macro used to carry two consecutive cards saying the same thing in the same
 * sentences. Fiscal Health rendered a fallback explaining that debt-to-GDP
 * cannot be sourced; SovereignContext, immediately below it, rendered the
 * identical explanation from `sovereign-gaps.ts`. The fallback had been
 * written to replace a hand-typed 67.2% and a green traffic light, which was
 * the right instinct — but it hardcoded prose that already existed.
 *
 * Two copies of a reason drift apart, and the copy that drifts is never the
 * one anybody corrects. Worse, the hardcoded one could not expire: the
 * `sovereign-gaps.ts` version is computed from what is present, so it stops
 * appearing by itself the day the figure starts arriving, while a hardcoded
 * card would keep apologising for a gap that had closed.
 *
 * So the rule is not "do not repeat yourself" as a style preference. It is
 * that an explanation of an absence must be generated from the absence, or it
 * will outlive it.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const PAGE = readFileSync(join(process.cwd(), 'src', 'app', 'macro', 'page.tsx'), 'utf8');
const GAPS = readFileSync(join(process.cwd(), 'src', 'lib', 'sovereign-gaps.ts'), 'utf8');

/**
 * Sentences sovereign-gaps.ts owns.
 *
 * Scoped to the gap declaration rather than the whole file. A first attempt
 * matched every quoted run in the source, and an apostrophe inside a comment
 * — "`worldbank.py` writes it" — paired with one two paragraphs later and
 * swallowed the real sentence along with it. The vacuity guard below caught
 * that, which is the entire reason it is there.
 */
function gapProse(): string[] {
  const block = GAPS.match(/const DEBT_TO_GDP_GAP[\s\S]*?\n\};/);
  if (!block) throw new Error('DEBT_TO_GDP_GAP not found — has the declaration been renamed?');
  return [...block[0].matchAll(/'([^']{30,})'/g)].map((m) => m[1]);
}

const squash = (s: string) => s.replace(/\s+/g, ' ').replace(/&apos;|&#39;/g, "'").trim();

describe('the sweep itself', () => {
  it('found the prose it is checking for, so this cannot pass vacuously', () => {
    const prose = gapProse();
    expect(prose.length, 'no gap explanation parsed out of sovereign-gaps.ts').toBeGreaterThan(1);
    for (const p of prose) expect(p.length).toBeGreaterThan(40);
  });
});

describe('the debt-to-GDP absence is explained once', () => {
  it('macro/page.tsx does not restate what sovereign-gaps.ts already says', () => {
    const page = squash(PAGE);
    const copied = gapProse()
      .map(squash)
      // Compare on a distinctive clause rather than the whole sentence, so a
      // reworded copy is caught as readily as a verbatim one.
      .filter((s) => page.includes(s.slice(0, 60)));

    expect(
      copied,
      'These sentences are generated by sovereign-gaps.ts and rendered by ' +
        'SovereignContext. Repeating them in the page puts the wording in two ' +
        'places to drift apart, and a hardcoded copy cannot expire when the ' +
        'figure starts arriving.'
    ).toEqual([]);
  });

  it('does not hardcode its own version of the same explanation', () => {
    const page = squash(PAGE);
    // The specific claim. If the page ever says this again in its own words,
    // there are two explanations for one absence.
    expect(page).not.toMatch(/We do not publish Kenya.{0,3}s debt-to-GDP ratio/i);
    expect(page).not.toMatch(/no observation in that series/i);
  });

  it('still renders Fiscal Health when the figures exist', () => {
    // Guarding the opposite overcorrection: removing the duplicate must not
    // remove the section itself.
    expect(PAGE).toContain('Fiscal Health');
    expect(PAGE).toContain('debt.debtToGDP !== null');
  });
});

describe('expectations sit beside the measurement they qualify', () => {
  it('renders MarketExpectations after Monetary Policy and before Fiscal Health', () => {
    const policy = PAGE.indexOf('── Monetary Policy ──');
    const expectations = PAGE.indexOf('<MarketExpectations />');
    const fiscal = PAGE.indexOf('── Fiscal Health ──');
    expect(policy).toBeGreaterThan(-1);
    expect(expectations).toBeGreaterThan(policy);
    expect(fiscal).toBeGreaterThan(expectations);
  });

  it('renders it exactly once', () => {
    expect(PAGE.match(/<MarketExpectations\s*\/>/g) ?? []).toHaveLength(1);
  });
});
